### ISSUE TITLE
Example on how to use wasmtime binary?

### ISSUE THREAD

**Issue by toxik** [bytecodealliance/ComponentizeJS#173]
Is there a way to successfully run `wasmtime hello.component.wasm` or `wasmtime serve hello.component.wasm` ?

```log
(main)⚡ [1] % wasmtime hello.component.wasm
Error: failed to run main module `hello.component.wasm`

Caused by:
    0: component imports instance `wasi:http/types@0.2.0`, but a matching implementation was not found in the linker
    1: instance export `fields` has the wrong type
    2: resource implementation is missing
```

```log
(main)⚡ [1] % wasmtime serve hello.component.wasm
Error: component imports instance `wasi:cli/terminal-input@0.2.2`, but a matching implementation was not found in the linker

Caused by:
    0: instance export `terminal-input` has the wrong type
    1: resource implementation is missing
```

**Comment by vados-cosmonic** [comment]
Hey @toxik to run a HTTP component with `wasmtime` you need to include the interfaces that you're going to use -- I *believe* that what you're missing is the `-S` argument to `wasmtime:

```console
wasmtime serve -S cli hello.component.wasm
```
Running `wasmtime <component>` implies use of the `wasi:cli` and in particular exporting `wasi:cli/run` -- would you mind sharing what your component WIT looks like, or maybe the output of `wasm-tools component wit <your component>` ?

For reference:

```
❯ wasmtime serve -S help
Available wasi options:

  -S                            cli[=y|n] -- Enable support for WASI CLI APIs, including filesystems, sockets, clocks, and random.
  -S             cli-exit-with-code[=y|n] -- Enable WASI APIs marked as: @unstable(feature = cli-exit-with-code)
  -S                         common[=y|n] -- Deprecated alias for `cli`
  -S                             nn[=y|n] -- Enable support for WASI neural network API (experimental)
  -S                        threads[=y|n] -- Enable support for WASI threading API (experimental)
  -S                           http[=y|n] -- Enable support for WASI HTTP API (experimental)
  -S                         config[=y|n] -- Enable support for WASI config API (experimental)
  -S                       keyvalue[=y|n] -- Enable support for WASI key-value API (experimental)
  -S                       listenfd[=y|n] -- Inherit environment variables and file descriptors following the systemd listen fd specification (UNIX only)
  -S                        tcplisten=val -- Grant access to the given TCP listen socket
  -S                       preview2[=y|n] -- Implement WASI CLI APIs with preview2 primitives (experimental).
  -S             nn-graph=<format>::<dir> -- Pre-load machine learning graphs (i.e., models) for use by wasi-nn.
  -S                inherit-network[=y|n] -- Flag for WASI preview2 to inherit the host's network within the guest so it has full access to all addresses/ports/etc.
  -S           allow-ip-name-lookup[=y|n] -- Indicates whether `wasi:sockets/ip-name-lookup` is enabled or not.
  -S                            tcp[=y|n] -- Indicates whether `wasi:sockets` TCP support is enabled or not.
  -S                            udp[=y|n] -- Indicates whether `wasi:sockets` UDP support is enabled or not.
  -S             network-error-code[=y|n] -- Enable WASI APIs marked as: @unstable(feature = network-error-code)
  -S                       preview0[=y|n] -- Allows imports from the `wasi_unstable` core wasm module.
  -S                    inherit-env[=y|n] -- Inherit all environment variables from the parent process.
  -S              config-var=<name>=<val> -- Pass a wasi config variable to the program.
  -S keyvalue-in-memory-data=<name>=<val> -- Preset data for the In-Memory provider of WASI key-value API.

pass `-S help-long` to see longer-form explanations
```

**Comment by toxik** [comment]
Thanks for the reply, Victor!

I was actually trying out the example from here https://github.com/bytecodealliance/ComponentizeJS/tree/main/example

I get a different error when trying -S cli, something related to HTTP. Trying out -S http gives the original error and I can’t seem to combine the two flags..

**Comment by vados-cosmonic** [comment]
Ah so you *can* combine the two!

```
wasmtime serve -S cli,http <component>
```

But I think the real problem here might be that we're encouraging building the component *without* dropping capabilities that are unneeded. The hello example actually *cannot* be run with `wasmtime`, because it is neither a component that exports `wasi:cli/run` for CLI-like execution *nor* a `wasi:http/incoming-handler` for web requests.

So probably at least a few changes need to be made:

- we should update [the build script](https://github.com/bytecodealliance/ComponentizeJS/blob/main/example/componentize.js) to drop unneeded features (this will at least get rid of the missing linker implementation errors)
- we should update the example to actually *be* something that is CLI-runnable (i.e. exports the `wasi:cli` world)
- we should probably update the documentation on the example to show how to use these things (or the component itself)

In the meantime, would you mind [using the examples in the `jco` project](https://github.com/bytecodealliance/jco/tree/main/examples/components)? You might find them a bit more approachable, and there's [a HTTP serving example](https://github.com/bytecodealliance/jco/tree/main/examples/components/http-hello-world) in there with the `wasmtime` invocation.

**Comment by vados-cosmonic** [comment]
Also, we'd absolutely welcome any PRs for updating the example in this repository! (feel free to copy all the stuff from `jco` :) )

**Comment by toxik** [comment]
Hey,

I ended up using `wash new component hello --template-name hello-world-typescript` (from https://wasmcloud.com/docs/tour/hello-world) and the result worked like a charm :)

Thanks!
